key_left = (keyboard_check(vk_left) || keyboard_check(ord("A")))
key_right = (keyboard_check(vk_right) || keyboard_check(ord("D")))
key_jump = (keyboard_check_pressed(vk_space) || keyboard_check_pressed(ord("W")) || keyboard_check_pressed(vk_up) || gamepad_button_check_pressed(0, gp_face1) || gamepad_button_check_pressed(0, gp_stickr))
key_slide = (keyboard_check(ord("S")) || keyboard_check(vk_down) || gamepad_button_check(0, gp_stickl) || gamepad_button_check(0, gp_face3))
key_crouch = (keyboard_check(vk_lcontrol) || keyboard_check(vk_rcontrol) || keyboard_check(ord("C")) || gamepad_button_check(0, gp_shoulderlb))
key_fire = (mouse_check_button_pressed(mb_left) || gamepad_button_check_pressed(0, gp_shoulderrb))
key_grenade = (mouse_check_button(mb_right) || gamepad_button_check(0, gp_shoulderr))
key_melee = (mouse_check_button_pressed(mb_middle) || keyboard_check_pressed(ord("E")) || gamepad_button_check_pressed(0, gp_face2) || gamepad_button_check_pressed(0, gp_shoulderl))
key_drop = (keyboard_check(ord("V")) || gamepad_button_check_pressed(0, gp_face4))
gui_width = display_get_gui_width()
gui_height = display_get_gui_height()
flash = 0
controller = 0
hascontrol = 1
hit = 0
hsp = 0
vsp = 0
grv = 0.3
walksp = 2.5
invincibility = 0
cangrenade = 1
maximumslide = 60
minimumslide = -1
canslide = 1
slide = maximumslide
slidecooldown = 3
doublejump = 0
smoketrail = 1
pause = 0
canstab = 1
stayonship = 0
shipdropoff = 0
smoke = 0
playerdeath = 0
cancontrol = 1
hitfrom = 0
jump_amount = 0
max_jumps = 2
deathscreen = 0
spawnonce = 1
cangrenade = 1
hascat = 0
signover = 0
reactivateguns = 0
fadeonce = 1
instance_create_layer(x, y, "Bullet_Layer", objforcefield)
vsync = 0
regularwalk = 1
jumpsprite = 0
