window_set_cursor(cr_none)
cursor_sprite = 384
var layer_id1 = layer_get_id("Backgrounds_MountainsClose")
var layer_id2 = layer_get_id("Backgrounds_MountainsNear")
var layer_id3 = layer_get_id("Backgrounds_MountainsFar")
var layer_id4 = layer_get_id("Backgrounds_Clouds")
var layer_id5 = layer_get_id("Backgrounds_Clouds2")
var layer_id6 = layer_get_id("Backgrounds_Planets")
var layer_id7 = layer_get_id("Backgrounds_Planets2")
var layer_id8 = layer_get_id("Backgrounds_Sky")
var layer_id9 = layer_get_id("Backgrounds_Foreground")
var layer_id10 = layer_get_id("Backgrounds_Ruins")
var layer_id11 = layer_get_id("Backgrounds_Clouds3")
layer_x(layer_id1, lerp(0, camera_get_view_x(view_camera[0]), 0.55))
layer_x(layer_id2, lerp(0, camera_get_view_x(view_camera[0]), 0.8))
layer_x(layer_id3, lerp(0, camera_get_view_x(view_camera[0]), 0.92))
layer_x(layer_id4, lerp(0, camera_get_view_x(view_camera[0]), 0.8))
layer_x(layer_id5, lerp(0, camera_get_view_x(view_camera[0]), 0.9))
layer_x(layer_id6, lerp(0, camera_get_view_x(view_camera[0]), 0.999))
layer_x(layer_id7, lerp(0, camera_get_view_x(view_camera[0]), 0.999))
layer_x(layer_id8, lerp(0, camera_get_view_x(view_camera[0]), 1))
layer_x(layer_id9, lerp(0, camera_get_view_x(view_camera[0]), -2))
layer_x(layer_id10, lerp(0, camera_get_view_x(view_camera[0]), 0.65))
layer_x(layer_id11, lerp(0, camera_get_view_x(view_camera[0]), 0.95))